name: CI

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  lint:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Execute Rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0','3.1','3.2']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec -f d spec/*.spec.rb
