name: CI

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile

  rspec:
    needs: rubocop
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7','3.0','3.1','3.2']
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle install
      - run: bundle exec rspec
